app:
  auth:
    accessTokenSecretKey: ENC(O4vakUdharL6NOlEcEdRn10XN5yNu/HvSYRz7Xgitbg=)
    accessTokenExpirationMsec: ENC(ehIy9SYQSTu4AvnlAEIBs7SySMQMp/Mh)
    refreshTokenSecretKey: ENC(48ntJIAL8AMwYe6smjbZApTFVmltL5MwvMIqHr73DEE=)
    refreshTokenExpirationMsec: ENC(JAudK4sDsTS9nluPxPbXBw5E+ifMdx8Y)
  oauth2:
    kakao:
      clientId: ENC(8kCNxoiABgNb/GbSLh6pG7ZKCF1BsVYXKohLOLIzL/LIdXpGogx+5goBuehE0jP4)
      clientSecret: ENC(OOfqSkIyZTtPrLMe7AgRdXw+XVFWx4gfQ7gyaZYZeJdmblhufCnnDaXTJY/NQZW9)
      tokenUri: https://kauth.kakao.com/oauth/token
      userInfoUri: https://kapi.kakao.com/v2/user/me
  openApi:
    careerNet:
      url: ENC(NSpGT4yKAQztUhct5Mfc2knA4MeXJ8EDu0whpZ7U3jZhafY652+DkmqAV+lVWd/yDA1xfKlqhSnmuXtIzlPasABYYqX7FwscEOh5Zh3HnXc4v2zXr0KHgC1r2CFw20Nnv1Ki0toVmp+VXSC7Y21p0QkC3NPcRsUhMH+iaf1Gk0RvDmEznxorrdK7IXyQur+40j9AB8xbJqYxAs23Ll+xxg==)

