spring:
  datasource:
    url: jdbc:h2:mem:momodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  config: classpath:logback/logback-local.xml