spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(YKbUmlpcg79I/gVDqyq7zIvXUk6x3Rv/gvfc4SNEUXWXtFh4WtO4tNHBkyppAfJSPi6vZg1v+fOiE/+kb4N/RE+mODm1Wkcl)
    username: ENC(ubjfUKNtnllAJV/VZzzXz52Ds1NosP4y)
    password: ENC(sGhQSsuBKB7Wty8/CRu2Oiv0VWNRVvt8)
    slave:
      slave1:
        name: slave-1
        url: ENC(5yIxAka7cDkoYwO2eYbOJrnOsA3di6/1ks3jC5OSkdW8hcZDvr743cX2rG7m/wmKIOknITNLZlEXSQSRQuInBrfuBGJpI89T)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
logging:
  slack:
    info-webhook-uri: ENC(IB1f1zikx4TT2VU7zN3NvxK9t4hCbvF8rdqpDsF5Ipbfbh2MHJ48b0Rr1/p6PhPnNU5drZgyOPmF3o/zV0lDxLYd4sDnGFigMg0zikgy2WVcP9xAPL/n6HpLIVCeUm47)
    warn-webhook-uri: ENC(h9RCzwCY9k5fWyH2Kk/zE2Nhhe1eUI/7gW3aocyFWAcw3TwQvVLDngiFxVpni4beNDbbiXbQtOv74BCXkOeeuHAV4sfePj3XY98zVDywCr8MliB/yhtffUI4oN7UqPYR)
    error-webhook-uri: ENC(2fsTNAh+xnNDCW5dQGIoAETS12W5yKa0gjt1gS2/JLY/T2RO60Yts5E0RJvaCFFWhMthI7oaD2pflW9z1B2CACay+xVGZhJEcqqf5wM+SnAFwU9GPfJx9LqtxoypmfJB)
  config: classpath:logback/logback-dev.xml
  bot-name: 모모 로그 알리미
  save-path: ./logs
  file-name: momo-dev

