spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(XUehUL5PPGL53umlTfwyYmvShVSdOGmCW1BpBxQm3hHdsitpU+b5CSc7m7s3/G02YhgEcj6qGKp5H/g0iyJa5doXTlxCG7SRFg/3fgk9gr8=)
      username: ENC(W/ReihaOVIn5l2mfJESNKA==)
      password: ENC(VaSZZ3vfWz/joImrJv73Wb+7d6Hssy/+)
  elasticsearch:
    rest:
      uris: ENC(+7VrSol4of46pDJtdtqu/ypr6OTHJwyMeHKH+GURehSo51A8R7YUU9MeBJ5ZIhhpf5fionGGg+xkiC+Q0/xyH4ziSmLH4f8Jw70cJJ9cnGlfUpfdtU69VZw6vFsC/pZYDsCajc11ZpU=)
      username: ENC(uKH9eLWahVpD1pyJCfRKlDLkwt5I2ntI)
      password: ENC(6gYFGu5lFh6fDF3P1+JT2dja+wtpvYf4)
#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
