spring:
  datasource:
    url: jdbc:h2:mem:momodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  config: classpath:logback/logback-local.xml
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE # elasticsearch 쿼리 로그
      hibernate:
        type:
          descriptor:
            sql: trace
