cloud:
  aws:
    credentials:
      accessKey: ENC(agGh7EXnupucL4Ln+Z6VY2sUcgb3xuJ3MfW1fTzyGE8=)
      secretKey: ENC(paoCYjsd4IhuupLDrHqrJma460ycvI5TzZDFAI+2FvRKadA5S7U4MR9aPu39bwyn6Geg7wRiZlE=)
    s3:
      bucket: ENC(Oh7jivXA0sKZVBMo5GoJByioVGC0K9hNFMKbdADqVTY=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
    elasticsearch:
      endpoint: ENC(+7VrSol4of46pDJtdtqu/ypr6OTHJwyMeHKH+GURehSo51A8R7YUU9MeBJ5ZIhhpf5fionGGg+xkiC+Q0/xyH4ziSmLH4f8Jw70cJJ9cnGlfUpfdtU69VZw6vFsC/pZYDsCajc11ZpU=)
      username: ENC(uKH9eLWahVpD1pyJCfRKlDLkwt5I2ntI)
      password: ENC(6gYFGu5lFh6fDF3P1+JT2dja+wtpvYf4)
