app:
  auth:
    access-token-secret-key: ENC(O4vakUdharL6NOlEcEdRn10XN5yNu/HvSYRz7Xgitbg=)
    access-token-expiration-msec: 180000
    refresh-token-secretKey: ENC(48ntJIAL8AMwYe6smjbZApTFVmltL5MwvMIqHr73DEE=)
    refresh-token-expiration-msec: 604800000
  oauth2:
    kakao:
      client-id: ENC(8kCNxoiABgNb/GbSLh6pG7ZKCF1BsVYXKohLOLIzL/LIdXpGogx+5goBuehE0jP4)
      client-secret: ENC(OOfqSkIyZTtPrLMe7AgRdXw+XVFWx4gfQ7gyaZYZeJdmblhufCnnDaXTJY/NQZW9)
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
  openApi:
    career-net:
      url: ENC(NSpGT4yKAQztUhct5Mfc2knA4MeXJ8EDu0whpZ7U3jZhafY652+DkmqAV+lVWd/yDA1xfKlqhSnmuXtIzlPasABYYqX7FwscEOh5Zh3HnXc4v2zXr0KHgC1r2CFw20Nnv1Ki0toVmp+VXSC7Y21p0QkC3NPcRsUhMH+iaf1Gk0RvDmEznxorrdK7IXyQur+40j9AB8xbJqYxAs23Ll+xxg==)
