spring:
  elasticsearch:
    rest:
      uris: ENC(+7VrSol4of46pDJtdtqu/ypr6OTHJwyMeHKH+GURehSo51A8R7YUU9MeBJ5ZIhhpf5fionGGg+xkiC+Q0/xyH4ziSmLH4f8Jw70cJJ9cnGlfUpfdtU69VZw6vFsC/pZYDsCajc11ZpU=)
      username: ENC(uKH9eLWahVpD1pyJCfRKlDLkwt5I2ntI)
      password: ENC(6gYFGu5lFh6fDF3P1+JT2dja+wtpvYf4)
  rabbitmq:
    host: ENC(4DD/ESXuJCNsHsrCDxFz4EdEg+zz63gb3bMQxXmFkc0=)
    port: ENC(h9eI7Rr6xafcNN3m+2LyaQ==)
    username: ENC(IZ/cubyov6uyFp8D4FwCrg==)
    password: ENC(WKyxHyx1sxeQb3NDvuMEYg==)
    routing-key: ENC(hfq2hNF6Mx/y0rFojPGXYlvpm+LUJw6f)
  data:
    mongodb:
      host: localhost
      port: 0
      database: test
  datasource:
    url: jdbc:h2:mem:momodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  config: classpath:logback/logback-local.xml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
